"use client";

import { useState } from "react";
import { Icon } from "./ui-icon";

export function LandingPreview({ module }: { module: string }) {
  const [choice, setChoice] = useState(0);
  const [expanded, setExpanded] = useState(false);
  const labels: Record<string, string> = { knowledge: "知识问答", assistant: "智能助手", approvals: "审批中心", logs: "执行日志", evaluation: "评测数据集", workspace: "工作空间" };
  return <div className={`landing-preview preview-${module}`} aria-label={`${labels[module]}交互示例`}>
    <div className="preview-bar"><span className="preview-dots" aria-hidden="true"><i /><i /><i /></span><strong>{labels[module]}</strong><span className="demo-label">交互示例</span></div>
    <div className="preview-body">
      {module === "knowledge" && <><p className="preview-context"><Icon name="book" /> 企业制度知识库</p><p className="preview-question">差旅报销需要准备哪些材料？</p><div className="preview-answer"><span className="preview-avatar"><Icon name="sparkles" /></span><div><strong>根据《差旅管理制度》</strong><p>请准备行程说明、费用明细及有效票据，按照规定提交申请。</p><button className="preview-citation" type="button" aria-expanded={expanded} onClick={() => setExpanded(!expanded)}><Icon name="file" /> [1] 差旅管理制度 · 第 3 节 <span>↗</span></button></div></div>{expanded && <div className="preview-excerpt"><strong>原文摘录</strong><p>“报销时应提供行程说明、费用明细及有效票据。”</p><small>合成资料，仅用于展示引用交互。</small></div>}<p className="preview-hint">点击引用，查看答案依据。</p></>}
      {module === "assistant" && <><div className="preview-tabs" aria-label="助手示例场景">{["知识问答", "信息查询", "权限申请"].map((label, index) => <button type="button" key={label} aria-pressed={choice === index} onClick={() => setChoice(index)}>{label}</button>)}</div><p className="preview-question">{["请介绍公司的差旅报销流程。", "帮我查询我的报销进度。", "我需要申请项目系统的访问权限。 "][choice]}</p><div className="preview-answer"><span className="preview-avatar"><Icon name="sparkles" /></span><div><strong>{["已找到相关知识", "查询结果", "需要人工审核"][choice]}</strong><p>{["为你整理了制度中的申请步骤，并附上原文引用。", "示例记录：已提交，待审核。此处仅展示查询结果形式。", "请提供系统名称与业务理由。提交后可在审批中心跟进。"][choice]}</p><span className="preview-status">{["有据可查", "只读查询", "先审后执行"][choice]}</span></div></div><div className="preview-composer">在平台中输入你的问题…<Icon name="arrow" /></div></>}
      {module === "approvals" && <><div className="preview-title-row"><strong>IT 系统访问申请</strong><span className="preview-status">{choice === 0 ? "待审核" : "已通过"}</span></div><dl className="preview-fields"><div><dt>目标系统</dt><dd>代码管理系统</dd></div><div><dt>业务理由</dt><dd>参与示例项目的日常协作</dd></div></dl><ol className="preview-flow"><li className="done">提交申请</li><li className={choice ? "done" : "current"}>人工审核</li><li className={choice === 2 ? "done" : ""}>模拟执行</li></ol><div className="preview-state-pair"><span>审批决定 <b>{choice ? "已通过" : "待审核"}</b></span><span>执行状态 <b>{choice === 2 ? "已成功" : "未执行"}</b></span></div><button className="preview-next" type="button" onClick={() => setChoice((choice + 1) % 3)}>{choice === 2 ? "重新查看示例" : "查看下一步"} <Icon name="arrow" /></button><p className="preview-hint">模拟流程，仅展示现有 IT 权限申请的步骤。</p></>}
      {module === "logs" && <><div className="preview-tabs" aria-label="日志示例筛选">{["全部记录", "成功", "失败"].map((label, index) => <button type="button" key={label} aria-pressed={choice === index} onClick={() => setChoice(index)}>{label}</button>)}</div><div className="preview-log"><span><Icon name="check" /><strong>{choice === 2 ? "权限边界校验" : "知识检索"}</strong></span><span className={choice === 2 ? "preview-failure" : "preview-status"}>{choice === 2 ? "已拒绝" : "成功"}</span></div><div className="preview-log"><span>示例调用 · {choice === 2 ? "20" : "320"} 毫秒</span><button type="button" className="feature-link" aria-expanded={expanded} onClick={() => setExpanded(!expanded)}>{expanded ? "收起详情" : "展开详情"}</button></div>{expanded && <dl className="preview-fields preview-excerpt"><div><dt>记录类型</dt><dd>{choice === 2 ? "权限拒绝" : "知识问答"}</dd></div><div><dt>执行结果</dt><dd>{choice === 2 ? "当前角色不具备操作权限" : "已返回带引用的回答"}</dd></div></dl>}<div className="preview-log faint"><span><Icon name="list" /> IT 权限申请</span><span>关联审批</span></div></>}
      {module === "evaluation" && <><div className="preview-tabs" aria-label="评测示例视图">{["测试用例", "运行结果"].map((label, index) => <button type="button" key={label} aria-pressed={choice === index} onClick={() => setChoice(index)}>{label}</button>)}</div>{choice === 0 ? <div className="preview-case-list">{[ ["知识问答", "回答是否包含引用"], ["工具调用", "申请是否需要审核"], ["权限边界", "是否拒绝未授权操作"] ].map(([type, title]) => <div key={type}><Icon name="file" /><span><strong>{title}</strong><small>{type}</small></span><span className="preview-status">启用</span></div>)}</div> : <><div className="preview-metrics"><div><strong>2 / 3</strong><span>通过用例</span></div><div><strong>100%</strong><span>评测覆盖</span></div><div><strong>320 ms</strong><span>平均耗时</span></div></div><div className="preview-log"><span>知识问答 / 引用要求</span><span className="preview-failure">未通过</span></div><p className="preview-hint">示例指标，展示如何定位预期与实际结果的差异。</p></>}<div className="preview-boundary"><Icon name="shield" /><span>仅使用合成或脱敏数据。工具仅模拟验证，不执行真实操作。</span></div></>}
      {module === "workspace" && <><div className="preview-tabs" aria-label="工作空间示例切换">{["产品团队", "运营团队"].map((label, index) => <button type="button" key={label} aria-pressed={choice === index} onClick={() => setChoice(index)}>{label}</button>)}</div><div className="preview-title-row"><strong>{choice ? "运营" : "产品"}工作空间</strong><span className="preview-status">独立空间</span></div><div className="preview-members">{[ ["林", "林小雨", "员工"], ["陈", "陈嘉宁", "知识管理员"], ["周", "周予安", "智能体管理员"], ["李", "李明", "系统管理员"] ].map(([initial, name, role]) => <div key={name}><span className="user-avatar">{initial}</span><strong>{name}</strong><span>{role}</span></div>)}</div><p className="preview-hint">示例成员与资源仅用于演示空间组织方式。</p></>}
    </div>
  </div>;
}
